### PR TITLE
Add iptables rule to puppet script to allow 0.0.0.0:8000

### PR DESCRIPTION
**Pull request by hassanNS**
Testing GET and query functions for Variants and Phenotype resources

Signed-off-by: Sheik Hassan solergiga@yahoo.com

### CODE REVIEW

**Comment by naegelyd** [comment]
This will need to wait on #233 and #234. Also, all of these tests can probably be merged into a single `resources` test module since we are only testing resources, not the full assessments, variants, phenotypes modules.

**Comment by naegelyd** [comment]
@muslimgiga Feel free to take a look at resolving #233. To get the assessment test to run in the test_suite, just re-add the line I removed in 19784788a

**Comment by hassanNS** [comment]
got it. I'll fix these

**Comment by naegelyd** [comment]
**NOTE:** THE COMMENTS IN THIS THREAD DO NOT ACTUALLY APPLY, THIS PR SOMEHOW GOT REPURPOSED. IGNORE THE COMMENTS, READ THE TITLE, AND LOOK AT THE COMMIT.

**Pull request merged**
